EspritAide/src/nadaBundle/Entity/fichier.php
<?php
/**
 * Created by PhpStorm.
 * User: mzark
 * Date: 18/02/2018
 * Time: 18:11
 */

namespace nadaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 *
 *
 * @ORM\Table(name="Fichier")
 * @ORM\Entity
 * @Vich\Uploadable
 */

class fichier
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="fichier")
     * @ORM\JoinColumn(name="id_user", referencedColumnName="id")
     */
    private $id_user;

    /**
     * @ORM\ManyToOne(targetEntity="Classe", inversedBy="fichier")
     * @ORM\JoinColumn(name="id_classe", referencedColumnName="id")
     */
    private $id_classe;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", nullable=true)
     */
    private $type;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", nullable=true)
     */
    private $nom;
    /**
     * @var string
     *
     * @ORM\Column(name="module", type="string", nullable=true)
     */
    private $module;

    /**
     * @ORM\Column(name="Datecreation",type="datetime", nullable=false)
     * @ORM\Version
     * @var \DateTime
     */
    public $reDatecreation = null;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getIdUser()
    {
        return $this->id_user;
    }

    /**
     * @param mixed $id_user
     */
    public function setIdUser($id_user)
    {
        $this->id_user = $id_user;
    }

    /**
     * @return mixed
     */
    public function getIdClasse()
    {
        return $this->id_classe;
    }

    /**
     * @param mixed $id_classe
     */
    public function setIdClasse($id_classe)
    {
        $this->id_classe = $id_classe;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * @return \DateTime
     */
    public function getReDatecreation()
    {
        return $this->reDatecreation;
    }

    /**
     * @param \DateTime $reDatecreation
     */
    public function setReDatecreation($reDatecreation)
    {
        $this->reDatecreation = $reDatecreation;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getModule()
    {
        return $this->module;
    }

    /**
     * @param mixed $module
     */
    public function setModule($module)
    {
        $this->module = $module;
    }




    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     *
     */
    public $imageFile;
    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     * @var string
     */
    public $imageName;
    /**
     * @ORM\Column(type="datetime",nullable=true)
     *
     * @var \DateTime
     */
    public $updatedAt;

    /**
     * FRepresent constructor.
     * @param null $reDatecreation
     */
    public function __construct()
    {
        $this->reDatecreation = new \DateTime();
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return fichier
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;
        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
        return $this;
    }
    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }
    /**
     * @param string $imageName
     *
     * @return fichier
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;
        return $this;
    }
    /**
     * @return string|null
     */
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

}

EspritAide/src/nadaBundle/Form/fichierType.php
<?php

namespace nadaBundle\Form;

use nadaBundle\Entity\fichier;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\PropertyAccess\PropertyPath;

class fichierType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('type')
            ->add('nom')
            ->add('module')
            ->add('idClasse',EntityType::class,array('class'=>'nadaBundle\Entity\Classe','choice_label'=>'niveau','multiple'=>false,))
            ->add('imageFile', VichFileType::class, [
                'required' => false,



            ]);

    }/**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'nadaBundle\Entity\fichier'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'nadabundle_fichier';
    }


}

EspritAide/src/nadaBundle/Controller/fichierController.php
<?php
/**
 * Created by PhpStorm.
 * User: mzark
 * Date: 20/02/2018
 * Time: 14:50
 */

namespace nadaBundle\Controller;

use nadaBundle\Entity\archivefichier;
use nadaBundle\Entity\fichier;
use nadaBundle\Form\fichierType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class fichierController extends Controller
{
    /**
     * @Route("/add_fichier",name="add_fichier")
     */
    public function addClasseAction(Request $request)
    {
        $user = $this->getUser();
        if (!is_object($user) ) {
            return $this->redirectToRoute('fos_user_security_login');
        }
        $id =  $this->getUser()->getId();

        $fichier = new fichier();
        $em=$this->getDoctrine()->getManager();
        $reno=$em->getRepository("nadaBundle:User")->findOneBy(array('id' => $id ));

        $user = $em->getRepository('nadaBundle:User')->findOneBy(array('id' => $id ));
        $form = $this->createForm(fichierType::class,$fichier );
        $form->handleRequest($request);
        if($form->isSubmitted() ) {
            $fichier->setIdUser($user);
            $em->persist($fichier);
            $em->flush();
            return $this->redirect($this->generateUrl('show_fichier',array('msg'=>"add successful")));
        }
        return $this->render('@nada/fichier/addfichier.html.twig',array(
            'form'=>$form->createView(),
            'user'=>$user,
            'userf'=>$reno
        ));
    }

    /**
     * @Route("/show_fichier",name="show_fichier")
     */
    public function show_fichierAction()
    {
        $user = $this->getUser();
        if (!is_object($user) ) {
            return $this->redirectToRoute('fos_user_security_login');
        }
        $id =  $this->getUser()->getId();
        $em=$this->getDoctrine()->getManager();
        $Profile = $em->getRepository('nadaBundle:User')->findOneBy(array('id' => $id ));
        $fichier = $em->getRepository('nadaBundle:fichier')->findBy(array('id_user' => $id ));
        $count=count($fichier);

        return $this->render('@nada/fichier/showfichier.html.twig',array(
            'fichier'=>$fichier,
            'userf'=>$Profile,
            "count"=>$count,

        ));

    }
    /**
     * @Route("/show_fichier_all",name="show_fichier_all")
     */
    public function ALLshow_fichierAction()
    {
        $user = $this->getUser();
        if (!is_object($user) ) {
            return $this->redirectToRoute('fos_user_security_login');
        }
        $id =  $this->getUser()->getId();
        $em=$this->getDoctrine()->getManager();
        $Profile = $em->getRepository('nadaBundle:User')->findOneBy(array('id' => $id ));
        $fichier = $em->getRepository('nadaBundle:fichier')->findAll();
        $count=count($fichier);

        return $this->render('@nada/fichier/showfichier.html.twig',array(
            'fichier'=>$fichier,
            'userf'=>$Profile,
            "count"=>$count,

        ));

    }
    /**
     * @Route("/edit_fichier/{idx}",name="edit_fichier")
     */
    public function editClientAction(Request $request,$idx)
    {
        $user = $this->getUser();
        $id =  $this->getUser()->getId();
        $email = $this->getUser()->getemail();


        if (!is_object($user) ) {

            return $this->redirectToRoute('fos_user_security_login');
        }
        else {    $em=$this->getDoctrine()->getManager();

            $reno=$em->getRepository("nadaBundle:User")->findOneBy(array('id' => $id ));
            $list=$em->getRepository("nadaBundle:fichier")->findOneBy(array('id' => $idx));
            $form = $this->createForm(fichierType::class,$list );



            $form->handleRequest($request);

            if($form->isSubmitted() )
            {

                $em->persist($list);
                $em->flush();

                //
                return $this->redirect($this->generateUrl('show_fichier'));

            }


            return $this->render('@nada/fichier/editfichier.html.twig',
                array("userf"=>$reno,"form"=>$form->createView()));
        }

    }
    /**
     * @Route("/archive_fichier/{id}",name="archive_fichier")
     */
    public function archiveAction($id)
    {
        $user = $this->getUser();
        if (!is_object($user) ) {
            return $this->redirectToRoute('fos_user_security_login');
        }
        $em=$this->getDoctrine()->getManager();
        $fichier = $em->getRepository('nadaBundle:fichier')->findOneBy(array('id' => $id ));
        $archive = new archivefichier();
        $archive->setId($fichier->getId());
        $archive->setIdUser($fichier->getIdUser());
        $archive->setIdClasse($fichier->getIdClasse());
        $archive->setType($fichier->getType());
        $archive->setNom($fichier->getNom());
        $archive->setModule($fichier->getModule());
        $archive->setReDatecreation($fichier->getReDatecreation());
        $archive->setImageName($fichier->getImageName());
        $archive->setUpdatedAt($fichier->getUpdatedAt());

        $em->persist($archive);
        $em->remove( $fichier);
        $em->flush();
        return $this->redirect($this->generateUrl('nada_default_index',array('msg'=>"Delete successful")));
    }
    /**
     * @Route("/show_archived",name="show_archived")
     */
    public function show_archivedAction()
    {
        $user = $this->getUser();
        if (!is_object($user) ) {
            return $this->redirectToRoute('fos_user_security_login');
        }
        $id =  $this->getUser()->getId();
        $em=$this->getDoctrine()->getManager();
        $Profile = $em->getRepository('nadaBundle:User')->findOneBy(array('id' => $id ));
        $fichier = $em->getRepository('nadaBundle:archivefichier')->findAll();
        $count=count($fichier);

        return $this->render('@nada/fichier/showarichived.html.twig',array(
            'fichier'=>$fichier,
            'userf'=>$Profile,
            "count"=>$count,

        ));

    }

}

EspritAide/src/nadaBundle/Resources/views/fichier/addfichier.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <aside class="right-side">
        <!-- Main content -->
        <section class="content-header" style="padding-left: 20px">

            <h4> Nouveau cours</h4>
            <ol class="breadcrumb">
                <li class="active">
                    <a href="{{ path('nada_default_index') }}">
                        <i class="livicon" data-name="home" data-size="16" data-color="#333" data-hovercolor="#333"></i>
                        Home
                    </a>
                </li>
                <li class="active">

                    Nouveau cours
                    </a>
                </li>
            </ol>
        </section>
        <section class="content">
            <section class="content paddingleft_right15">

                <div class="row">

                    <div class="col-md-4">
                        <div class="panel">
                            <div class="panel-heading" style="background-color: #A6192E;color:#ffffee">
                                <h4 class="panel-title">
                                    <i class="livicon" data-name="user" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                                    Information du cours
                                </h4>
                            </div>
                            {{ form_start(form) }}
                            <div class="panel-body">
                                <div class="field-input">
                                    <label> Nom du cours </label>

                                    {{ form_widget(form.nom, {'id':'nom','attr': {'class': 'form-control','placeholder':'nom' }}) }}
                                </div>

                                <div class="field-input">
                                    <label> Module</label>

                                    {{ form_widget(form.module, {'id':'module','attr': {'class': 'form-control','placeholder':'Nom module' }}) }}
                                </div>
                                <div class="field-input">
                                    <label> Niveau</label>

                                    {{ form_widget(form.idClasse, {'id':'Niveau','attr': {'class': 'form-control','placeholder':'Niveau' }}) }}
                                </div>
                                <div class="field-input">
                                    <label> Type</label>

                                    {{ form_widget(form.type, {'id':'numero','attr': {'class': 'form-control','placeholder':' Type' }}) }}
                                </div>
                                <div class="download-btn">
                                    <label> fichier</label>

                                    {{ form_widget(form.imageFile, {'id':'numero','attr': {'class': 'form-control','placeholder':' Fichier' }}) }}
                                    <br>
                                </div>

                                <br>
                                <div>

                                    <input class="btn btn-lg btn-block" style="background-color: #A6192E; color: #ffffee; " type="submit" id="_submit" name="_submit" value="{{ 'Nouveau cours'|trans }}" />

                                </div>
                                {{ form_end(form) }}




                            </div>
                        </div></div>


                </div>




            </section>
        </section>
    </aside>


{% endblock%}

EspritAide/src/nadaBundle/Resources/views/fichier/showCoursFront.html.twig
{% extends 'baseFront.html.twig' %}

{% block A %}
    <embed src="{{ asset('images/products/'~list.imageName) }}" width="1485" height="700" type='application/pdf'>
<center><a href="{{ asset('images/products/'~list.imageName) }}"  class=" img-fluid "  download="" alt="riot">download<a></center>
    <div class="line-divider"></div>
    {% for user in comment %}

        <div class="post-comment">
        <img src="{{ asset('images/products/'~user.idUser.imageName) }}" alt="" class="profile-photo-sm" />
        <p><a href="" class="profile-link">{{ user.idUser.reNom }} {{ user.idUser.rePrenom }}</a><i class="em em-laughing"></i>
        {{ user.commentaire }}
            <br>
            <a href="{{ path('delete_comment',{'id': user.id}) }}">supprimer</a>
        </p>
    </div>
        {% endfor %}
    {{ form_start(form) }}
    <div class="post-comment">
        <img src="{{ asset('images/products/'~user.imageName) }}" alt="" class="profile-photo-sm" />
        {{ form_widget(form.commentaire, {'id':'commentaire','attr': {'class': 'form-control','placeholder':' Post a comment','type':'text' }}) }}


    </div>
    <div>

        <input class="btn btn-lg btn-block" style="background-color: #A6192E; color: #ffffee; " type="submit" id="_submit" name="_submit" value="{{ 'Comment'|trans }}" />

    </div>
    {{ form_end(form) }}
{% endblock %}

EspritAide/src/nadaBundle/Resources/views/fichier/showFrontCours.html.twig
{% extends 'baseFront.html.twig' %}
{%  block pagestyle %}
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/app/vendors/datatables/css/dataTables.bootstrap.css') }}" />

    <link href="{{ asset('bundles/app/css/pages/tables.css') }}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/app/vendors/datatables/css/dataTables.colReorder.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/app/vendors/datatables/css/dataTables.scroller.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/app/vendors/datatables/css/dataTables.bootstrap.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('jTable/jquery.dataTables.min.css') }}" />

{% endblock %}
{% block A %}

    <!-- Right side column. Contains the navbar and content of the page -->
    <aside class="right-side">
        <!-- Content Header (Page header) -->


        <!-- Main content -->
        <section class="content paddingleft_right15">

            <div class="row">
                <div class="panel">
                    <div class="panel-heading" style="background-color: #A6192E;color:#ffffee">
                        <h4 class="panel-title">
                            <i class="livicon" data-name="user" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                            Liste des cours
                        </h4>
                    </div>
                    <br />
                    <div class="col-md-2 static">
                        <div class="suggestions" id="sticky-sidebar">
                            <h4 class="grey">Les cours</h4>
                            {% for user in fichier %}

                            <div class="follow-user">
                                <img src="{{ asset('images/products/'~user.idUser.imageName) }}" style="max-height: 100px ; max-width: 100px" class="profile-photo-sm pull-left"  alt="riot">
                                <a href="{{ path("cours",{'idx':user.id}) }}">
                                </a>
                                <div>
                                    <h5><a href="{{ path("cours",{'idx':user.id}) }}">{{ user.nom }}</a></h5>
                                    <a href="{{ path("cours",{'idx':user.id}) }}" class="text-green">{{ user.type }}</a>
                                </div>
                            </div>
                            {% endfor %}



                        </div>
                        </div>

                </div>
            </div>

            <!-- row--> </section>
    </aside>

{% endblock %}
{% block js %}
    <script>
        $('#count').each(function () {
            $(this).prop('Counter',0).animate({
                Counter: $(this).text()
            }, {
                duration: 2500,
                easing: 'swing',
                step: function (now) {
                    $(this).text(Math.ceil(now));
                }
            });
        });
    </script>
    <script type="text/javascript" src="{{ asset('jTable/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript">$(document).ready(function() {
            $('#table').DataTable();
        } );
    </script>
{% endblock %}

EspritAide/src/nadaBundle/Resources/views/fichier/showarichived.html.twig
{% extends 'base.html.twig' %}
{%  block pagestyle %}
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/app/vendors/datatables/css/dataTables.bootstrap.css') }}" />

    <link href="{{ asset('bundles/app/css/pages/tables.css') }}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/app/vendors/datatables/css/dataTables.colReorder.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/app/vendors/datatables/css/dataTables.scroller.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/app/vendors/datatables/css/dataTables.bootstrap.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('jTable/jquery.dataTables.min.css') }}" />

{% endblock %}
{% block body %}
    <!-- Right side column. Contains the navbar and content of the page -->
    <aside class="right-side">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>Nos Cours </h1>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ path('nada_default_index') }}">
                        <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                        Dashboard
                    </a>
                </li>

                <li class="active">Les Cours Archivée</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content paddingleft_right15">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6 margin_10 animated fadeInLeftBig">
                    <!-- Trans label pie charts strats here-->
                    <div class="lightbluebg no-radius"style="background-color: #515763">
                        <div class="panel-body squarebox square_boxs">
                            <div class="col-xs-12 pull-left nopadmar">
                                <div class="row">
                                    <div class="square_box col-xs-7 text-right">
                                        <span>Cours</span>
                                        <div class="number" id="count">{{ count }}</div>
                                    </div>
                                    <i class="livicon pull-right" data-name="notebook" data-loop="true" data-color="#ffffff" data-hovercolor="#ffffee" data-size="70"></i>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 margin_10 animated fadeInLeftBig">
                    <!-- Trans label pie charts strats here-->
                    <div class="lightbluebg no-radius" style="background-color: #A6192E"><a href="{{ path('add_fichier') }}">
                            <div class="panel-body squarebox square_boxs">
                                <div class="col-xs-12 pull-left nopadmar">
                                    <div class="row">
                                        <div class="square_box col-xs-7 text-right">
                                            <span style="color: #ffffff;">Nouveau cours </span>
                                            <div class="number">  <i class="livicon pull-right" data-name="plus" data-loop="true" data-color="#ffffff" data-hovercolor="#ffffee" data-size="40"></i>

                                            </div>
                                        </div>
                                        <i class="livicon pull-right" data-name="notebook" data-loop="true" data-color="#ffffff" data-hovercolor="#ffffee" data-size="70"></i>

                                    </div>
                                    <div class="row">

                                    </div>


                                </div>
                            </div></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="panel">
                    <div class="panel-heading" style="background-color: #A6192E;color:#ffffee">
                        <h4 class="panel-title">
                            <i class="livicon" data-name="user" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                            Liste des cours
                        </h4>
                    </div>
                    <br />
                    <div class="panel-body">

                        <table id="table" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th> Nom </th>
                                <th> Module </th>
                                <th> Niveau </th>
                                <th> fichier </th>
                                <th> Ajouter par </th>
                                <th> PDF </th>


                            </tr>
                            </thead>
                            <tfoot>

                            <tr>
                                <th> Nom </th>
                                <th> Module </th>
                                <th> Niveau </th>
                                <th> fichier </th>
                                <th> Ajouter par </th>
                                <th> PDF </th>



                            </tr>
                            </tfoot>

                            <tbody>

                            {% for user in fichier %}
                                <tr>



                                    <td>   {{ user.nom }} </td>
                                    <td>    {{ user.module  }} </td>
                                    <td>    {{ user.idClasse.niveau  }} </td>

                                    <td>      <a href="{{ asset('images/products/'~user.imageName) }}"  class=" img-fluid "  download="" alt="riot">download</a> </td>
                                    <td>    {{ user.idUser.reNom  }} {{ user.idUser.reprenom  }} </td>
                                    <td>                                     <embed src="{{ asset('images/products/'~user.imageName) }}" width="500" height="375" type='application/pdf'>
                                    </td>







                                </tr>






                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>

                        <!-- Modal for showing delete confirmation -->

                    </div>
                </div>
            </div>

            <!-- row--> </section>
    </aside>
{% endblock %}
{% block js %}
    <script>
        $('#count').each(function () {
            $(this).prop('Counter',0).animate({
                Counter: $(this).text()
            }, {
                duration: 2500,
                easing: 'swing',
                step: function (now) {
                    $(this).text(Math.ceil(now));
                }
            });
        });
    </script>
    <script type="text/javascript" src="{{ asset('jTable/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript">$(document).ready(function() {
            $('#table').DataTable();
        } );
    </script>
{% endblock %}